    # Allocating shared memory for the 'limit_conn' module
    limit_conn_zone $binary_remote_addr   zone=limit_conn_binary_remote_addr:10m;

    # Allocating shared memory for the 'limit_req' module
    limit_req_zone  $binary_remote_addr   zone=limit_req_binary_remote_addr:10m    rate=1r/s;

    # For logging with msecs
    map "$time_local:$msec" $time_local_w_ms { ~(^\S+)(\s+\S+):\d+.(\d+)$ $1.$3$2; }

    log_format  custom  '$remote_addr:$remote_port - $remote_user [$time_local_w_ms] $scheme://$host:$request_port "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/angie/access.log  custom;

    gzip  on;


    zstd            on;
    zstd_min_length 256;
    zstd_comp_level 3;
    zstd_types      text/plain text/css text/xml text/javascript
                    application/json application/javascript
                    application/x-javascript application/xml
                    application/xml+rss application/atom+xml
                    image/svg+xml;


server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name example.com www.example.com _;

    ssl_certificate     /etc/angie/ssl/certs/wordpress.local.crt;
    ssl_certificate_key /etc/angie/ssl/keys/wordpress.local.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    http2 on;

    index index.php index.html index.htm;

    root /var/www/html;

    status_zone https;

    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        status_zone https_wordpress;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;

            limit_conn limit_conn_binary_remote_addr 5;
            limit_req zone=limit_req_binary_remote_addr burst=5 nodelay;

            status_zone https_wordpress_.php;
        }

        location ~ /\.ht {
            deny all;
        }

        location = /favicon.ico {
            log_not_found off; access_log off;
        }

        location = /robots.txt {
            log_not_found off; access_log off; allow all;
        }

        location ~ ^/wp-content/cache {
            deny all;
        }

        location ~* /(?:uploads|files)/.*\.php$ {
            deny all;
        }

        location ~* \.(css|gif|ico|jpeg|jpg|js|png|woff2)$ {
            expires max;
            log_not_found off;

            status_zone https_wordpress_static;
        }
    }

    location /console/ {

        satisfy any;

        # Только локальный анонимный доступ
        allow 127.0.0.1;
        allow ::1;
        deny all;

        # или, если не локальный, то по auth_basic
        auth_basic           "Identify yourself!";
        auth_basic_user_file /etc/angie/http.d/htpasswd;

        auto_redirect on;

        alias /usr/share/angie-console-light/html/;
        # Только во FreeBSD:
        # alias /usr/local/www/angie-console-light/html/;
        index index.html;

        status_zone https_console;

        location /console/api/ {
            api /status/;

            status_zone https_console_api;
        }
    }
}
